theme: jekyll-theme-cayman

title: Pimpri-Chinchwad-Engineers
description: 

github:
  is_user_page: false
  is_project_page: false 
  
# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com
    icon: twitter
  - name: Facebook
    url: https://facebook.com
    icon: facebook
    
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
